### ISSUE TITLE
Is there additional documentation available?

### ISSUE THREAD

**Issue by itcontrol-ca** [inovector/mixpost#84]
### Detailed description

I've been at this for days and am about to give up. I was going to purchase a business license, but wanted to test first and am glad I did.

I've tried docker - whats the script at the begging of the page? Am I suppose to use it? 

I'm not familiar with portainer io and its not part of the instructions? 
Can you make a video installing it via terminal?

I tried to get into discord, but it looks like its shut off?

I eventually thought I installed via the package method, but when I go to the site it forwards to the /mixpost domain but the requested URL is not found? 

I don't see any error logs, etc that I can access.

I'm having a pretty hard time with this install for some reason.

**Comment by uhlhosting** [comment]
The documentation works also for docker or non docker environments. One will use that what suits them. What issues you had in deploying the docker compose. One does not need portainer to make it work. Right there is a bonus for the unskilled users of CLI docker in general id say.

**Comment by paulrobertf** [comment]
I've attempted both docker and package. I am able to get to a point where I have the laravel app permissions issue, then I update the permissions. Once I resolve that I am met with a request server not found.

I'm able to connect to a test .html and .php page that I make. All services are running. Server is configured. Not sure what I did wrong/how to check?

**Comment by uhlhosting** [comment]
@paulrobertf please email ask@inovector.com with everything outlined and a link to this issue, the developer will take a look and most probably by tomorrow he will contact you there to see ways in assisting you.

Let me know how that works out.

**Comment by uhlhosting** [comment]
@paulrobertf just seen the discord mention, can you tell me what discord invite link you tried, and where you found it? We made some changes to the discord invite URL. We may have missed some in the change process.

**Comment by paulrobertf** [comment]
Thanks, I just ended up contacting sales to see if they would support me with deployment if I purchase the pro license. I really need this thing going like last week.

That discord link you just sent worked on my phone, so I was able to join, thanks. Still doesn't work on my PC though, strange. Pretty sure there is a permalink option for discord channels.

**Comment by uhlhosting** [comment]
@itcontrol-ca I am sure they will get your instance up and running in no time.

**Comment by uhlhosting** [comment]
@itcontrol-ca im not sure there is a web form. Other than the chat. Thats why I suggested you to email the dev directly.

**Comment by itcontrol-ca** [comment]
> @itcontrol-ca im not sure there is a web form. Other than the chat. Thats why I suggested you to email the dev directly.

I emailed them yesterday, and have been trying to get anyone to help in discord. No luck so far, this is incredibly frustrating. I see others with deployment issues as well and not getting any support. Please review your deployment strategy and stream-line it, better, or update your documentation. The video you have for the portainer.io install is outdated, which adds another layer of confusion.

**Comment by itcontrol-ca** [comment]
> @itcontrol-ca im not sure there is a web form. Other than the chat. Thats why I suggested you to email the dev directly. 

I tried emailing again, and nothing. Tried Live Chat and got no response for hours until someone said hi I'm here at the end before the Chat went offline. 

I give up on this system. Support isn't sufficient enough to use for business. This needs to be fixed or this will die like socioboard.

**Comment by lao9s** [comment]
Hi @itcontrol-ca 

I'm sorry you're having trouble installing Mixpost, but:

1. Read about our support (screenshot attached). We try to help where we can, but we cannot provide support for every custom installation.
2. It seems that you are using Mixpost Lite, so the support is "Community support".
3. It seems that we are in different time zones (I'm on GMT +2).
4. Self-hosting solutions implies having technical knowledge, knowing how to technically run docker containers or how to configure a VPS server. If you can't handle it, you are free to choose another cloud service.
5. The fact that you receive an error does not mean that the problem is in the software, you must realize what you are not doing correctly and try again.

**Comment by uhlhosting** [comment]
> > @itcontrol-ca im not sure there is a web form. Other than the chat. Thats why I suggested you to email the dev directly.
> 
> I tried emailing again, and nothing. Tried Live Chat and got no response for hours until someone said hi I'm here at the end before the Chat went offline.
> 
> I give up on this system. Support isn't sufficient enough to use for business. This needs to be fixed or this will die like socioboard.

NO it wont die like socioboard, because the two have nothing in common, and compared to a developer that faces the rushes of many like "you", well is hard to grow, develop, offer support, when people are not rational. Mixpost is a great project, worth every penny, and will grow into a even better product, we all learn, I have seen BIG companies failing at support, so while that, please be reasonable, that is all. The more users base grows, there will be people paid to handle support more, yet every growth had to start somewhere. @lao9s is an amazing developer, yet he ain't good for everyones desires, reasons, and reasoning that are so... many ways to manifest.
